name: 编译dsm

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  build:
    runs-on: ubuntu-latest
    name: 编译 "${{matrix.platform}} ${{matrix.version}}"
    strategy:
      fail-fast: false
      matrix:
       include:
         - platform: apollolake
           version: 7.0.1-42218

    steps:
      - name: 准备结束
        uses: actions/checkout@v2

      - name: 缓存加速
        uses: actions/cache@v2
        with:
          path: |
            cache/*.pat
            docker/downloads/*.txz
          key: ${{matrix.platform}}-${{matrix.version}}-${{ hashFiles('global_config.json') }}
          
      - name: 准备构建环境
        run: |
          ./redpill_tool_chain.sh build ${{matrix.platform}}-${{matrix.version}}
          
      - name: Chmod
        run: chmod 0755 ./build-ds918-7.0.1.sh

      - name: 编译引导镜像
        run: ./build-ds918-7.0.1.sh auto  ${{matrix.platform}}-${{matrix.version}}


      - name: 上传引导镜像到 github actions
        uses: actions/upload-artifact@v2
        with:
          name: dsm-${{matrix.platform}}-${{matrix.version}}
          path: images/redpill-DS[39]*.img
          if-no-files-found: error
